name: Feature Request
description: Suggest a new feature or enhancement for Wise Mise MCP
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We love hearing ideas from the community.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: What would you like to see added to Wise Mise MCP?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
        How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: domain
    attributes:
      label: Domain Area
      description: Which domain does this feature relate to?
      options:
        - Task Analysis
        - Task Creation
        - Task Management
        - Domain Experts
        - MCP Integration
        - Documentation
        - Performance
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical for adoption
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: |
        Add any other context or screenshots about the feature request here.
        
        Examples of similar features in other tools, mockups, or code snippets are helpful!